test

diff --git a/.github/workflows/playwright.yml b/.github/workflows/playwright.yml
--- a/.github/workflows/playwright.yml
+++ b/.github/workflows/playwright.yml
@@ -25,12 +25,52 @@ jobs:
         name: playwright-report
         path: playwright-report/
         retention-days: 30
-    - name: Push the new files to github pages
-    # This will create a separate branch called gh-pages where it will store only reports. And from where it will push all future changes 
-    # to github pages. Having a separate branch will keep the reports and changes commits separate to your main/master
-      uses: peaceiris/actions-gh-pages@v3
+publish_report:
+  name: Publish HTML Report
+  # using always() is not ideal here, because it would also run if the workflow was cancelled
+  if: "success() || needs.test.result == 'failure'"
+  needs: [test]
+  runs-on: ubuntu-latest
+  continue-on-error: true
+  env:
+    # Unique URL path for each workflow run attempt
+    HTML_REPORT_URL_PATH: reports/${{ github.ref_name }}/${{ github.run_id }}/${{ github.run_attempt }}
+  steps:
+    - name: Checkout GitHub Pages Branch
+      uses: actions/checkout@v2
       with:
-        github_token: ${{ secrets.GITHUB_TOKEN }}
-        publish_dir: ./playwright-report # from what folder to take files. It takes only contents
-        destination_dir: ${{ steps.timestampid.outputs.timestamp }} # a sub-directory where to publish to avoid overwriting other reports
-        
+        ref: gh-pages
+    - name: Set Git User
+      # see: https://github.com/actions/checkout/issues/13#issuecomment-724415212
+      run: |
+        git config --global user.name "github-actions[bot]"
+        git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
+    - name: Download zipped HTML report
+      uses: actions/download-artifact@v2
+      with:
+        name: playwright-report
+        path: ${{ env.HTML_REPORT_URL_PATH }}
+    - name: Push HTML Report
+      timeout-minutes: 3
+      # commit report, then try push-rebase-loop until it's able to merge the HTML report to the gh-pages branch
+      # this is necessary when this job is running at least twice at the same time (e.g. through two pushes at the same time)
+      run: |
+        git add .
+        git commit -m "workflow: add HTML report for run-id ${{ github.run_id }} (attempt:  ${{ github.run_attempt }})"
+
+        while true; do
+          git pull --rebase
+          if [ $? -ne 0 ]; then
+            echo "Failed to rebase. Please review manually."
+            exit 1
+          fi
+
+          git push
+          if [ $? -eq 0 ]; then
+            echo "Successfully pushed HTML report to repo."
+            exit 0
+          fi
+        done
+    - name: Output Report URL as Worfklow Annotation
+      run: |
+        FULL_HTML_REPORT_URL=https://ysfaran.github.io/playwright-gh-actions-gh-pages/$HTML_REPORT_URL_PATH
